### ISSUE TITLE
can't find rust.css

### ISSUE THREAD

**Issue by davekong** [steveklabnik/rustbook#22]
When building and reading a book locally the file rust.css can't be located leading to ugly formatting.

To reproduce:
``` 
git clone https://github.com/steveklabnik/rustbook.git
cd rustbook
cargo build
cd ..
git clone git@github.com:rust-lang/rust-guidelines.git
cd rust-guidelines
../rustbook/target/rustbook build
chromium-browser _book/index.html
```

**Comment by steveklabnik** [comment]
We have since moved rust-guidelines into the rust repo, so it may just not be maintained at this point.
