### ISSUE TITLE
Pointers: Boxes: Best Practices: Recursive Data Structures Minor example issue.

### ISSUE THREAD

**Issue by wldcordeiro** [steveklabnik/rustbook#23]
Currently in this section you show the output as
`Cons(1, Box(Cons(2, Box(Cons(3, Box(Nil))))))`
when what is output looks like
`Cons(1, Cons(2, Cons(3, Nil)))`
Just a minor issue, I was going to submit a PR but I can't seem to find the content of this page in the repo.

**Comment by steveklabnik** [comment]
Hey @wldcordeiro ! sorry about this, I just saw it now.

I'm not sure what you're asking, as this is a tool for building documentation, we don't have any of this here. Do you remember what this issue was about?

**Comment by wldcordeiro** [comment]
Oh @steveklabnik didn't realize that this isn't the source for the Book. It was just an issue with the book's content.

**Comment by steveklabnik** [comment]
ah! yes, the book is in `src/doc/trpl` in the rust repo.

**Comment by wldcordeiro** [comment]
Thanks for letting me know @steveklabnik I'll just make a PR over there then.

**Comment by steveklabnik** [comment]
Thanks! :smile: :+1:
