### ISSUE TITLE
Support for non-rustbook links in ToC

### ISSUE THREAD

**Issue by hawkw** [steveklabnik/rustbook#26]
Here's a feature request:

I'm using Rustbook to prepare documentation for a project implemented in Rust. I'd really like to be able to include RustDoc-generated API documentation as 'chapters' in my Rustbook-generated page's table of contents. Currently, if you include links to non-Rustbook files in `SUMMARY.md`, this makes Rustbook panic: 
```
$ rustbook build
thread '<main>' panicked at 'arithmetic operation overflowed', src/book.rs:140
```

It'd be awfully nice if there was an easy way to do this (other than manually editing the Rustbook-generated HTML files; I'm lazy).

**Comment by steveklabnik** [comment]
Interesting, wonder why this happens.

**Comment by steveklabnik** [comment]
can you file this against rust-lang/rust if you are still interested? this is just a mirror
