### ISSUE TITLE
Can't include custom anchors to headings

### ISSUE THREAD

**Issue by mkpankov** [steveklabnik/rustbook#28]
I tried something like this:

```
### <a name="head1234"></a>A Heading in this SO entry!
```
from this [answer](http://stackoverflow.com/questions/6695439/how-do-you-create-link-to-a-named-anchor-in-multimarkdown).

It doesn't work - rustbook simply strips the custom anchor.

We need such functionality to fix anchor links to headings of some sub-sections (like `glossary.html#abstract-syntax-tree`). Currently we have `# Abstract syntax tree` translated to `# Абстрактное синтаксическое дерево (Дерево абстрактного синтаксического анализа)` and it goes totally nuts, since urlencode will turn such a link into `glossary.html#%D0%90%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D0%BE%D0%B5-%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5-%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE-%28%D0%94%D0%B5%D1%80%D0%B5%D0%B2%D0%BE-%D0%B0%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE-%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%29` which is unbearable.

So we need a way to specify alternative anchor name for linking.

**Comment by steveklabnik** [comment]
Can you file this against rust-lang/rust please? This is just a mirror.
