### ISSUE TITLE
Features needed for feature parity with Gitbook

### ISSUE THREAD

**Issue by sinistersnare** [steveklabnik/rustbook#3]
Hey, I was wondering what was necessary for porting a project such as [rust-by-example](https://github.com/japaric/rust-by-example) to Rust-book. 

Thanks :)

**Comment by steveklabnik** [comment]
I'm not 100% sure. Rust by example uses some scripts to do pre and post processing, we could probably keep the same things in place there.

This is a bit open-ended, so I'm closing it, but we should certainly eventually move over.
